variables:
  API_TOKEN: "$ACCESS_TOKEN"
  FORCE_DEPLOY: "false"
  
include:
  - project: gitlab-instance-8c9d9f19/dev-tools/continuous-integration
    file: 
      - /node/install.gitlab-ci.yml
      - /node/audit.gitlab-ci.yml
      - ssh.gitlab-ci.yml
      - create-release.gitlab-ci.yml
      - generate-changelog.gitlab-ci.yml
      - workflow.gitlab-ci.yml

audit-modules:
  variables:
    AUDIT_LEVEL: critical


deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
    - if: $FORCE_DEPLOY == "true"
  before_script: 
    - apt install curl -y
    - !reference [ .install-node, before_script ]
    - !reference [.configure-ssh, before_script]
  script:
    - VERSION=$( npm pkg get version | tr -d '"')
    - 'curl --request POST --header "PRIVATE-TOKEN: ${API_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${VERSION}&ref=master"'
    - ionic build --prod
    - scp -r $CI_PROJECT_DIR/www ${PROD_USER}@${PROD_server}:~
    - scp install.sh ${DEPLOY_USER}@${DEPLOY_SERVER}:~
    - ssh ${DEPLOY_USER}@${DEPLOY_SERVER} "bash install.sh"
  artifacts:
    paths:
      - plutus/
    name: "ExpenseUI"
    when: on_success
